// =========================================================================
// ⚙️ CONFIGURATION (Config.gs)
// =========================================================================

const CONFIG = Object.freeze({
  SHEET_NAMES: Object.freeze({
    MASTER_DYNO_LOG: "Master_Dyno_Log",
    PART_REFERENCE_MATRIX: "Part_Reference_Matrix",
    OPERATOR_STATION: "Operator_Station",
    PROGRAM_REGISTRY: "Program_Registry"
  }),

  // 🔒 DEV-SAFE FOLDER TARGETS
  FOLDERS: Object.freeze({
    WATCH_FOLDER: "01_Watch_Folder_DEV",
    ARCHIVE_FOLDER: "02_Archive_DEV"
  }),

  COLUMNS: Object.freeze({
    MASTER_DYNO_LOG: Object.freeze({
      TIMESTAMP: 1, PROGRAM_NAME: 2, TRUE_SERIAL: 3, BASE_MODEL: 4, VALVING_VERSION: 5, ROD_FORCE: 6,
      SPEED_1: 7, COMP_1: 8, REB_1: 9, SLOPE_1: 10, LOOP_AREA_1: 11,
      SPEED_2: 12, COMP_2: 13, REB_2: 14, LOOP_AREA_2: 15,
      SPEED_3: 17, COMP_3: 18, REB_3: 19,
      TEST_1_STATUS: 22, TEST_2_STATUS: 23, OVERALL_STATUS: 24,
      DIAGNOSTICS: 25, TEARDOWN_ACTION: 26, ENG_COMMENTS: 27
    }),

    PART_REFERENCE_MATRIX: Object.freeze({
      PROGRAM_NAME: 1, SPEED_1: 2, SPEED_2: 3, SPEED_3: 4,
      COMP_1_MEAN: 5, COMP_1_SD: 6, COMP_1_MIN: 7, COMP_1_MAX: 8,
      REB_1_MEAN: 9, REB_1_SD: 10, REB_1_MIN: 11, REB_1_MAX: 12,
      SLOPE_1_MIN: 13, LOOP_AREA_1_MIN: 14,
      COMP_2_MEAN: 15, COMP_2_SD: 16, COMP_2_MIN: 17, COMP_2_MAX: 18,
      REB_2_MEAN: 19, REB_2_SD: 20, REB_2_MIN: 21, REB_2_MAX: 22,
      HEALTH_STAMP: 26, CONTROL_MODE: 27, SAMPLE_COUNT: 29
    }),

    PROGRAM_REGISTRY: Object.freeze({
      PROGRAM_NAME: 1, BASE_MODEL: 3, VALVING_VERSION: 7
    })
  }),

  OPERATOR_STATION: Object.freeze({
    RANGES: Object.freeze({
      BARCODE_INPUT: "C2", FILE_LINK_OUTPUT: "C3", BOM_REV_OUTPUT: "C4",
      PART_NO_OUTPUT: "C5", PROGRAM_NAME_OUTPUT: "C16", CACHED_FILE_ID: "Z1",
      LIMIT_C1_MIN: "B22", LIMIT_C1_MAX: "C22", LIMIT_R1_MIN: "D22", LIMIT_R1_MAX: "E22",
      LIMIT_C2_MIN: "B23", LIMIT_C2_MAX: "C23", LIMIT_R2_MIN: "D23", LIMIT_R2_MAX: "E23",
      LIMIT_SLOPE: "F22", STATUS_BANNER_TOP: "A8", STATUS_BANNER_MAIN: "A11",
      CLEAR_METADATA_RANGE: "C3:C5", CLEAR_RESULTS_RANGE: "A27:L100",
      RESULTS_START_ROW: 27, RESULTS_START_COL: 1, RESULTS_COL_COUNT: 12
    })
  }),

  NOMINAL_SPEEDS: Object.freeze([100, 400, 1000, 2500]),

  STATUS: Object.freeze({
    PASS: "PASS", FAIL: "FAIL", FAIL_BLUEPRINT: "FAIL (BLUEPRINT)",
    FAIL_OUTLIER: "FAIL (OUTLIER)", OVERRIDE_PASS: "PASS (OVERRIDE)",
    INITIALIZING: "INITIALIZING", NOT_RUN: "NOT RUN", NOT_TESTED: "NOT TESTED YET"
  }),

  DIAGNOSTIC_TAGS: Object.freeze({
    ROD_FORCE_FAIL: "[RF_FAIL]", COMP_1_FAIL: "[C1_FAIL]", REB_1_FAIL: "[R1_FAIL]",
    COMP_2_FAIL: "[C2_FAIL]", REB_2_FAIL: "[R2_FAIL]", SLOPE_FAIL: "[SLOPE_FAIL]"
  })
});